name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install CocoaPods
        run: |
          brew update
          brew install cocoapods

      - name: Flutter Pub Get
        run: flutter pub get

      - name: CocoaPods install (force update)
        working-directory: ios
        run: |
          pod repo update
          pod install
          pod update Firebase/Messaging GoogleUtilities/UserDefaults

      - name: Build iOS App (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos/Runner.app
