name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v3

      # 2. Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # 3. Install CocoaPods via Homebrew
      - name: Install CocoaPods
        run: |
          brew update
          brew install cocoapods

      # 4. Fetch Dart & Flutter dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 5. Override the Firebase iOS SDK version in your Podfile
      #    This forces Cocoapods to use Firebase iOS SDK 11.x, which
      #    resolves the Messaging vs GoogleUtilities/UserDefaults conflict.
      - name: Override Firebase iOS SDK Version
        run: |
          # Insert at top of ios/Podfile:
          sed -i '' "1iENV['FIREBASE_IOS_SDK_VERSION'] = '11.0.0'" ios/Podfile

      # 6. Install pods (this will pick up the overridden SDK version)
      - name: CocoaPods install
        working-directory: ios
        run: |
          pod repo update
          pod install --verbose

      # 7. Build the iOS app without code signing
      - name: Build iOS App (no codesign)
        run: flutter build ios --release --no-codesign

      # 8. Upload the un-signed .app bundle as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos/Runner.app
